#ifndef __COLORS_H
#define __COLORS_H


enum
{
// background
  COLOR_BACKGROUND = 0,

// players
  COLOR_FIRST_PLAYER = 1, COLOR_LAST_PLAYER  =  4,

// shots
  COLOR_LASER1 = 5, COLOR_LASER2, COLOR_LASER3, COLOR_LASER4 = 8,
  COLOR_BULLET = 9,
  COLOR_FIRST_FLAME = 16, COLOR_LAST_FLAME = 31,

// infobar colors
  COLOR_INFOBAR_DEFAULT = 32, COLOR_INFOBAR_LIGHT, COLOR_INFOBAR_DARK,
  COLOR_INFOBAR_INTERNAL, COLOR_INFOBAR_ARMOR, COLOR_INFOBAR_SHIELD,
  COLOR_INFOBAR_ENERGY = 38,
  
  COLOR_INFOBAR_SHIP = 48, COLOR_INFOBAR_FIRST_DEVICE,
  COLOR_INFOBAR_LAST_DEVICE = 63,

// sticky substances
  COLOR_FIRST_WATER = 64, COLOR_LAST_WATER = 67,
  COLOR_FIRST_SLIME1 = 68, COLOR_LAST_SLIME1 = 71,
  COLOR_FIRST_SLIME2 = 72, COLOR_LAST_SLIME2 = 75,

// bases
  COLOR_FIRST_BASE = 80, COLOR_LAST_BASE = 83,
  COLOR_PL1_BASE = 84, COLOR_PL2_BASE, COLOR_PL3_BASE, COLOR_PL4_BASE = 87,

// ground
  COLOR_FIRST_INDESTRUCTIBLE = 88, COLOR_LAST_INDESTRUCTIBLE = 111,
  COLOR_FIRST_TURNS_INTO_WATER = 112, COLOR_LAST_TURNS_INTO_WATER = 115,
  COLOR_FIRST_TURNS_INTO_SLIME1 = 116, COLOR_LAST_TURNS_INTO_SLIME1 = 119,
  COLOR_FIRST_TURNS_INTO_SLIME2 = 120, COLOR_LAST_TURNS_INTO_SLIME2 = 123,
  COLOR_FIRST_SOFT_GROUND = 128, COLOR_LAST_SOFT_GROUND = 159,
  COLOR_FIRST_NORMAL_GROUND = 160, COLOR_LAST_NORMAL_GROUND = 255
};


#endif
